services:
  postgres:
    image: postgres:16
    container_name: alugueis-festivos-db
    restart: no
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts_sql:/scripts_sql
      - ./scripts_sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

