@baseUrl = http://localhost:3001/api


### =========================================
### POST - Criar CLIENTE
### =========================================
POST {{baseUrl}}/clientes
Content-Type: application/json

{
  "nome": "Maria",
  "sobrenome": "Oliveira",
  "email": "maria.oliveira@email.com",
  "telefone": "85999998888",
  "endereco": "Rua das Flores, 123 - Fortaleza/CE",
  "cpf": "00844435376"
}

### =========================================
### GET - Listar todos
### =========================================
GET {{baseUrl}}/clientes
Content-Type: application/json
