@baseUrl = http://localhost:3001/api
@id_categoria = 3

### =========================================
### POSTS - Criar CATEGORIA
### =========================================
POST {{baseUrl}}/categorias
Content-Type: application/json

{
  "nome" : "Arco",
  "descricao" : "Estrutura circular"
}

### =========================================
### GET - Listar todas
### =========================================
GET {{baseUrl}}/categorias
Content-Type: application/json


### =========================================
### PUT - Editar categoria
### =========================================
PATCH {{baseUrl}}/categorias/{{id_categoria}}
Content-Type: application/json

{
  //"nome" : "Arco de Cobre"
  "descricao" : "estrutura circular Cobreee"
}
