@baseUrl = http://localhost:3001/api


### =========================================
### POSTS - Criar CATEGORIA
### =========================================
POST {{baseUrl}}/categorias
Content-Type: application/json

{
  "nome" : "Boleira",
  "descricao" : "Estrutura para bolo"
}

### =========================================
### GET - Listar todas
### =========================================
GET {{baseUrl}}/categorias
Content-Type: application/json
